version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      - checkout
      - run: mvn test
      - run: cat target/surefire*
workflows:
  version: 2
  default:
    jobs: 
      - test

